name: SimpleHelpTickets
main: me.odium.simplehelptickets.SimpleHelpTickets
version: 1.6
commands:
   sht:
      aliases: [helptickets, simplehelptickets]
      description: Help Menu
      permission:
      usage: /sht
   ticket:
      aliases: [helpme, grief]
      description: Open a help ticket
      permission: sht.ticket
      usage: /ticket <Description>
   tickets:
      description: Review your/all help tickets
      permission:
      usage: /tickets [ac]  
   closeticket:
      description: close or reopen a help ticket
      permission:
      usage: /closeticket [r] <#>
   replyticket:
      aliases: [rticket]
      description: reply to a help ticket
      permission: sht.ticket
      usage: /replyticket <#> <reply>
   taketicket:
      description: Assign self to a help ticket
      permission: sht.admin
      usage: /taketicket <#>
   checkticket:
      aliases: [chticket]
      description: check your/a help ticket
      permission:
      usage: /checkticket <#>
   delticket:
      aliases: [dticket]
      description: Delete a ticket
      permission:
      usage: /delticket <#>
   purgetickets:
      aliases: [ptickets]
      description: Purge all expired tickets
      permission: sht.purge
      usage: /purgetickets